### ISSUE TITLE
How use coincenter as library?

### ISSUE THREAD

**Issue by dedetuga** [sjanel/coincenter#218]
hi,
I'm trying to use coincenter as library on linux qt c++ but when i compile following [With cmake](https://github.com/sjanel/coincenter/blob/main/INSTALL.md#with-cmake)  with the command 
`mkdir -p build && cd build
CC=gcc-10 CXX=g++-10 cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCCT_ENABLE_TESTS=ON -DCCT_BUILD_EXEC=OFF -DCCT_ENABLE_ASAN=OFF ..
ninja`

I'm gettiing the static libraries and i'm not able to load them to qt creator

how can i use the static libraries?

**Comment by sjanel** [comment]
Hello,

You need to import `coincenter` for your project in your `CMakeLists.txt`.
The simplest way to do this is to use `FetchContent`:
```
include(FetchContent)

FetchContent_Declare(
  coincenter
  GIT_REPOSITORY https://github.com/sjanel/coincenter.git
  GIT_TAG        main
)

FetchContent_MakeAvailable(coincenter)
```
And then, let's say your projects have source files in the `src` directory where you want to include `coincenter.hpp` (for instance), you just need to add:
```
aux_source_directory(src SRC_FILES)

add_executable (myProgram ${SRC_FILES})
target_link_libraries(myProgram PRIVATE coincenter)
```

Here is how your project files should look like:
```
"myProgram"
  | "CMakeLists.txt" (containing what is explained above)
  | "src"
       | main.cpp (containing #include "coincenter.hpp" for instance)
```

Go to `myProgram` directory, and launch the command that you gave, it should work. If it's not clear enough, I will update documentation and create a project example.

Thanks for your interest in `coincenter`!

**Comment by sjanel** [comment]
After one year of inactivity, I assume that this issue is no more relevant.
